### ISSUE TITLE
Vertical scroll is not working

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-app#3]
The global property `html, body { overflow: hidden }` ([source code](https://github.com/worona/worona-app/blob/dev/client/packages/core-app-worona/src/app/loading-app-theme-worona/components/Theme/style.css#L5)) is blocking the vertical scroll of the theme.

**Comment by luisherranz** [comment]
Could you redo the loading theme without that?

**Comment by Poliuk** [comment]
Sure! I'll fix it myself tomorrow.

**Comment by luisherranz** [comment]
Great!
